// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE2RN-1d0BBQ19uUpxQw274OD6WgkprYE',
    appId: '1:55012167377:web:1cb73806e5aed881643ff0',
    messagingSenderId: '55012167377',
    projectId: 'chatapp-83301',
    authDomain: 'chatapp-83301.firebaseapp.com',
    storageBucket: 'chatapp-83301.appspot.com',
    measurementId: 'G-PX878MS1GK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0j2st2zo-lHgQSyQRq95fNJjWl4_YSiw',
    appId: '1:55012167377:android:211e957f435e5796643ff0',
    messagingSenderId: '55012167377',
    projectId: 'chatapp-83301',
    storageBucket: 'chatapp-83301.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7l_VFgltQIW9kwiBMcwz6VLMZZkXWwqI',
    appId: '1:55012167377:ios:41129a2441e88a83643ff0',
    messagingSenderId: '55012167377',
    projectId: 'chatapp-83301',
    storageBucket: 'chatapp-83301.appspot.com',
    iosClientId: '55012167377-9km7l1a51c2sfhquk9uf9uds0obro0td.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7l_VFgltQIW9kwiBMcwz6VLMZZkXWwqI',
    appId: '1:55012167377:ios:c21e29b4e498616f643ff0',
    messagingSenderId: '55012167377',
    projectId: 'chatapp-83301',
    storageBucket: 'chatapp-83301.appspot.com',
    iosClientId: '55012167377-pi9nisiq8d9fnvtrc9eb0s407i7j9g2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
